# Generated by Django 6.0.7 on 2026-07-25 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DosageForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosage_form_id", models.IntegerField(null=True, unique=True)),
                ("dosage_form_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=250, unique_for_date="created")),
                ("brand_names_count", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "dosage form",
                "verbose_name_plural": "dosage forms",
                "ordering": ("dosage_form_name",),
            },
        ),
        migrations.CreateModel(
            name="DrugClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_class_id", models.IntegerField(null=True, unique=True)),
                ("drug_class_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=250, unique_for_date="created")),
                ("generics_count", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "drug class",
                "verbose_name_plural": "drug classes",
                "ordering": ("drug_class_name",),
            },
        ),
        migrations.CreateModel(
            name="Indication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indication_id", models.IntegerField(null=True, unique=True)),
                ("indication_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=250, unique_for_date="created")),
                ("generics_count", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "indication",
                "verbose_name_plural": "indications",
                "ordering": ("indication_name",),
            },
        ),
        migrations.CreateModel(
            name="Generic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generic_id", models.IntegerField(null=True, unique=True)),
                ("generic_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=250, unique_for_date="created")),
                ("monograph_link", models.TextField(blank=True, null=True)),
                ("indication_description", models.TextField(blank=True, null=True)),
                (
                    "therapeutic_class_description",
                    models.TextField(blank=True, null=True),
                ),
                ("pharmacology_description", models.TextField(blank=True, null=True)),
                ("dosage_description", models.TextField(blank=True, null=True)),
                ("administration_description", models.TextField(blank=True, null=True)),
                ("interaction_description", models.TextField(blank=True, null=True)),
                (
                    "contraindications_description",
                    models.TextField(blank=True, null=True),
                ),
                ("side_effects_description", models.TextField(blank=True, null=True)),
                (
                    "pregnancy_and_lactation_description",
                    models.TextField(blank=True, null=True),
                ),
                ("precautions_description", models.TextField(blank=True, null=True)),
                (
                    "pediatric_usage_description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "overdose_effects_description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "duration_of_treatment_description",
                    models.TextField(blank=True, null=True),
                ),
                ("reconstitution_description", models.TextField(blank=True, null=True)),
                (
                    "storage_conditions_description",
                    models.TextField(blank=True, null=True),
                ),
                ("descriptions_count", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "drug_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generics",
                        to="crawler.drugclass",
                    ),
                ),
                (
                    "indication",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generics",
                        to="crawler.indication",
                    ),
                ),
            ],
            options={
                "verbose_name": "generic",
                "verbose_name_plural": "generics",
                "ordering": ("generic_name",),
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer_id", models.IntegerField(null=True, unique=True)),
                ("manufacturer_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=250, unique_for_date="created")),
                ("generics_count", models.IntegerField(blank=True, null=True)),
                ("brand_names_count", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "manufacturer",
                "verbose_name_plural": "manufacturers",
                "ordering": ("manufacturer_name",),
                "indexes": [
                    models.Index(
                        fields=["manufacturer_name"], name="crawler_MANF_name_index"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_id", models.IntegerField(null=True, unique=True)),
                ("brand_name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("allopathic", "Allopathic"), ("herbal", "Herbal")],
                        default="allopathic",
                        max_length=12,
                    ),
                ),
                ("slug", models.SlugField(max_length=250, unique_for_date="created")),
                (
                    "dosage_form",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("strength", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "package_container",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pack_size_info",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Package Size",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "generic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="crawler.generic",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="crawler.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "medicine",
                "verbose_name_plural": "medicines",
                "ordering": ("brand_name",),
            },
        ),
        migrations.AddIndex(
            model_name="generic",
            index=models.Index(
                fields=["generic_name"], name="crawler_generic_name_index"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["brand_name"], name="crawler_medicine_name_index"
            ),
        ),
    ]
